### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by cemo** [tgroshon/amplify2terraform#10]
👋 @tgroshon ,

I am trying to prototype a backend infrastructure based on mostly terraform. I wanted to see your current situation about lambdas. Are you still using serverless framework? I will be glad that if you provide more information about it. Thank for sharing project, it is inspiring.

**Comment by tgroshon** [comment]
@cemo Sorry for the late reply.  To answer your question regarding Lambdas, yes I am still using Serverless.  I have been interested in looking more deeply into the tools around AWS SAM, and specifically the Arc/Architect tool: https://arc.codes/docs/en/get-started/quickstart.

For now, the Serverless tool has done what I've needed, and is mature enough to be very predictable.

As far as I've found, most of the Lambda management tools use Cloudformation, so you end up with a mixed model of Terraform and Cloudformation.  It is what it is 🤷 .

I would love to hear about things you try out and learn!  Best of luck.
